export enum BlockID {
  Air = 0,
  Grass = 1,
  Dirt = 2,
  Stone = 3,
  CoalOre = 4,
  IronOre = 5,
  Bedrock = 6,
  OakLog = 7,
  Leaves = 8,
  TallGrass = 9,
  FlowerRose = 10,
  FlowerDandelion = 11,
  RedstoneLamp = 12,
  StoneBrick = 13,
  Water = 14,
  Lava = 15,
  Sand = 16,
  Sandstone = 17,
  Gravel = 18,
  SnowGrass = 19,
  Snow = 20,
  SpruceLog = 21,
  SpruceLeaves = 22,
  BirchLog = 23,
  BirchLeaves = 24,
  Cactus = 25,
  DeadBush = 26,
  GoldOre = 27,
  DiamondOre = 28,
}

/**
 * Ore veins per chunk: number of vein attempts, blob size and the y range
 * (inclusive) they may spawn in. Roughly follows Minecraft's distribution
 * scaled to a 128-block world.
 */
export const oreConfig = {
  coal: { id: BlockID.CoalOre, attempts: 12, size: 12, minY: 5, maxY: 120 },
  iron: { id: BlockID.IronOre, attempts: 10, size: 7, minY: 2, maxY: 64 },
  gold: { id: BlockID.GoldOre, attempts: 2, size: 6, minY: 2, maxY: 32 },
  diamond: { id: BlockID.DiamondOre, attempts: 1, size: 5, minY: 1, maxY: 16 },
};

export const blockIdToKey = {
  [BlockID.Air]: "air",
  [BlockID.Grass]: "grass",
  [BlockID.Dirt]: "dirt",
  [BlockID.Stone]: "stone",
  [BlockID.CoalOre]: "coal",
  [BlockID.IronOre]: "iron",
  [BlockID.Bedrock]: "bedrock",
  [BlockID.OakLog]: "oak_log",
  [BlockID.Leaves]: "leaves",
  [BlockID.TallGrass]: "tall_grass",
  [BlockID.FlowerRose]: "flower_rose",
  [BlockID.FlowerDandelion]: "flower_dandelion",
  [BlockID.RedstoneLamp]: "redstone_lamp",
  [BlockID.StoneBrick]: "stone_brick",
  [BlockID.Water]: "water",
  [BlockID.Lava]: "lava",
  [BlockID.Sand]: "sand",
  [BlockID.Sandstone]: "sandstone",
  [BlockID.Gravel]: "gravel",
  [BlockID.SnowGrass]: "snow_grass",
  [BlockID.Snow]: "snow",
  [BlockID.SpruceLog]: "spruce_log",
  [BlockID.SpruceLeaves]: "spruce_leaves",
  [BlockID.BirchLog]: "birch_log",
  [BlockID.BirchLeaves]: "birch_leaves",
  [BlockID.Cactus]: "cactus",
  [BlockID.DeadBush]: "dead_bush",
  [BlockID.GoldOre]: "gold_ore",
  [BlockID.DiamondOre]: "diamond_ore",
};
